image: breezewaredev/alpine-13openjdk-3.6-maven:latest

options:
  max-time: 3

definitions: 
  steps:
    - step: &verify-config
        name: Verify Technology config
        script:
          - which java
          - which mvn
    - step: &build-artifacts
        caches:
          - maven
        name: Build project
        max-time: 2
        script:
          - mvn clean validate
          - mvn clean package -Dmaven.test.skip=true

pipelines:
  branches:
    '**':   
    - step: *verify-config
    - step: *build-artifacts

    master:
    - step:
        name: Build artifacts for 'master' branch
        script:
          - echo "Running pipeline from $BITBUCKET_BRANCH branch"
    - step: *verify-config
    - step: *build-artifacts

    '{release/*,feature/*}':
      - step:
          name: Build artifacts for 'release/*' or 'feature/*' branch
          script:
            - echo "Running pipeline from $BITBUCKET_BRANCH branch"
      - step: *verify-config
      - step: *build-artifacts

  tags:
    DF_*:
      - step: *verify-config
      - step: *build-artifacts
      - step:
          name: Deploy artifacts to Nexus Repository when 'tag' is created
          script:
            - echo "Triggering pipeline for tag '$BITBUCKET_TAG'"
            - cat settings.xml
            - bash update-settings-dot-xml.sh
            - cat settings.xml
            - mvn -s settings.xml clean deploy -Dmaven.test.skip=true
