<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>remove_feature</name>
   <tag></tag>
   <elementGuidId>645a0c80-c3d8-419b-a81c-e93564513002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[1]/div/div/div[2]/form/div[2]/div[1]/div[6]/div/div/div[3]/button</value>
   </webElementProperties>
</WebElementEntity>
