package net.breezeware.dynamo.shipping.ups.dto.pickup;

import lombok.Data;
import net.breezeware.dynamo.shipping.ups.dto.Response;

/**
 * DTO to persits all the {@link PickupCreationResponse}.
 */
@Data
public class PickupCreationResponse {

    private Response response;

    /**
     * Pickup Request Number generated by UPS pickup system when a successful pickup
     * is scheduled
     */
    private String PRN;

    private RateStatus rateStatus;

    private RateResult rateResult;

}
